# Generated by Django 3.2.6 on 2021-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (0, 'Unknown')], verbose_name='Sex')),
                ('profession', models.CharField(max_length=128, verbose_name='Profession')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=128, verbose_name='Phone')),
                ('status', models.IntegerField(choices=[(0, 'Apply'), (1, 'Pass'), (2, 'Reject')], default=0, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Student Information',
            },
        ),
    ]
