# Generated by Django 3.2.6 on 2021-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=128, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profession',
            field=models.CharField(max_length=128, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qq',
            field=models.CharField(max_length=128, verbose_name='qq'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (0, 'Unknown')], verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'Apply'), (1, 'Pass'), (2, 'Reject')], default=0, verbose_name='status'),
        ),
    ]
