# Generated by Django 3.2.6 on 2021-09-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, 'Latest posts'), (3, 'Most popular posts'), (4, 'Latest comments')], default=1, verbose_name='display_type')),
                ('content', models.CharField(blank=True, help_text='If it is not set in HTML format, it can be blank', max_length=500, verbose_name='content')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Show'), (0, 'Hide')], default=1, verbose_name='status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Side Bar',
                'verbose_name_plural': 'Side Bar',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('href', models.URLField(verbose_name='href')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Delete')], default=1, verbose_name='status')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Blogs with high weight will be displayed in the front', verbose_name='weight')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Link',
            },
        ),
    ]
