# Generated by Django 3.2.6 on 2021-09-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('website', models.URLField(verbose_name='website')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Delete')], default=1, verbose_name='status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='target')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
            },
        ),
    ]
